# Generated by Django 4.1.3 on 2023-04-07 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=120)),
                ('income', models.FloatField(default=2, max_length=30)),
                ('expenses', models.FloatField(default=2, max_length=30)),
                ('balance', models.FloatField(default=2, max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
