# Generated by Django 4.1.3 on 2023-04-07 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
