# Generated by Django 4.1.3 on 2023-04-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_alter_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='balance',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='descriptions',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='expenses',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='income',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
