# Generated by Django 4.1.3 on 2023-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_register_totales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='totales',
            field=models.FloatField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
