# Generated by Django 4.1.3 on 2023-04-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0007_remove_register_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='totall',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
